"""--- Day 7: Laboratories ---
You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At that point, the original beam stops, and two new beams are emitted from the splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
Those beams continue downward until they reach more splitters:

.......S.......
.......|.......
......|^|......
......|.|......
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
This process continues until all of the tachyon beams reach a splitter or exit the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|
To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?

Your puzzle answer was 1507.

The first half of this puzzle is complete! It provides one gold star: *

--- Part Two ---
With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
...|^.^...^....
...|...........
..|^.^...^.^...
..|............
.|^...^.....^..
.|.............
|^.^.^.^.^...^.
|..............
Or, there's the timeline where the particle alternated going left and right at each splitter:

.......S.......
.......|.......
......|^.......
......|........
......^|^......
.......|.......
.....^|^.^.....
......|........
....^.^|..^....
.......|.......
...^.^.|.^.^...
.......|.......
..^...^|....^..
.......|.......
.^.^.^|^.^...^.
......|........
Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
....^|^...^....
.....|.........
...^.^|..^.^...
......|........
..^..|^.....^..
.....|.........
.^.^.^|^.^...^.
......|........
In this example, in total, the particle ends up on 40 different timelines.

Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?"""

from collections import deque    
import numpy as np

file_path = "data/test_d7.txt"

# file_path = "data/input_day7.txt"

FIRST_PART = False

def count_splits(grid):
    splits = 0
    begin = grid[0].index("S") # S is the start point in the first row
    queue = deque()
    queue.append((0, begin))
    visited = set()

    while len(queue) > 0:
        x, y = queue.popleft()
        if (x, y) in visited or x < 0 or x >= len(grid) or y < 0 or y >= len(grid[0]):
            continue
        visited.add((x, y))
        if grid[x][y] == '^': # split point
            splits += 1
            queue.append((x+1, y-1)) # go down left
            queue.append((x+1, y+1)) # and down right
        elif grid[x][y] == '.' or grid[x][y] == 'S': # normal path
            queue.append((x+1, y)) # go down
        else:
            print("Encountered obstacle at", x, y)
            continue
    return splits

def count_quantum_splits_memoization(grid):
    
    begin = grid[0].index("S") # S is the start point in the first row
    memo = {}

    def count_paths(x, y):
        if (x, y) in memo:
            return memo[(x, y)]
        if x < 0 or x >= len(grid) or y < 0 or y >= len(grid[0]):
            return 1
        
        if grid[x][y] == '^': # split point
            result = count_paths(x+1, y-1) + count_paths(x+1, y+1) # go down left and down right
        elif grid[x][y] == '.' or grid[x][y] == 'S': # normal path
            result = count_paths(x+1, y) # go down
        else:
            print("Encountered obstacle at", x, y)
            return -1
        memo[(x, y)] = result
        return result
    
    return count_paths(0, begin)

def count_quantum_splits_DP(grid):
    dp_grid = np.zeros(shape=(len(grid), len(grid[0])), dtype=int)
    begin = grid[0].index("S") # S is the start point in the first row

    for x in range(len(grid)-1, -1, -1):
        for y in range(len(grid[0])):
            if grid[x][y] == '.' or grid[x][y] == 'S': # normal path
                dp_grid[x][y] = dp_grid[x+1][y] if x+1 < len(grid) else 1
            elif grid[x][y] == '^': # split point
                dp_grid[x][y] = dp_grid[x][y] + dp_grid[x+1][y-1] if x+1 <len(grid) and y-1>=0 else dp_grid[x][y] + 1
                dp_grid[x][y] = dp_grid[x][y] + dp_grid[x+1][y+1] if x+1 <len(grid) and y+1 < len(grid[0]) else dp_grid[x][y] + 1

            else:
                print("Encountered obstacle at", x, y)
                dp_grid[x][y] = 0
    print (dp_grid)
    return dp_grid[0][begin]

if __name__ == "__main__":

    with open(file=file_path, mode="r+") as file:
        lines = file.readlines()
        # read the grid
        grid = []
        for line in lines:
            grid.append(line.rstrip("\n"))
                
        if FIRST_PART:
            split_sum = count_splits(grid)
            print("Final split_sum", split_sum, ".")
        else:
            # timeline_count = count_quantum_splits_memoization(grid)
            timeline_count = count_quantum_splits_DP(grid)
            print("Final timeline_count", timeline_count, ".")